### ISSUE TITLE
Repo Creation Request: sigstore/smimecosign

### ISSUE THREAD

**Issue by wlynch** [sigstore/TSC#14]
**Description**

Following up on https://github.com/sigstore/cosign/issues/865 - this issue proposes creation of a new repo `sigstore/smimecosign` to move https://github.com/wlynch/smimecosign to a sigstore-owned repository.

smimecosign is a tool for generating and verifying Git commit signatures using ephemeral Fulcio certs.

Naming bikeshedding welcome!

**Comment by dlorenc** [comment]
+1!

**Comment by lukehinds** [comment]
I would be more inclined to go for sigstore-smime as cosign is centered on oci registry artefacts. 

The other option is gitsign (as more people will know what git is rather than smime).

Added this to the TSC meeting on the 12th,

**Comment by lukehinds** [comment]
appproved: will create repo initially as gitsign
