### ISSUE TITLE
Transfer jvanzyl/sigstore-maven repository into Sigstore's Github organization

### ISSUE THREAD

**Issue by jvanzyl** [sigstore/TSC#15]
Hi,

I have a fully working Maven plugins for doing complete signing (PGP/SSH/X509) of Maven artifacts for deployment into Maven Central that I'd like to contribute.

If this is amenable to the TAC I'd like to transfer the following repository:

https://github.com/jvanzyl/maven-sigstore/settings

An example of a deployment to Maven Central using the plugin can be found here:

https://repo1.maven.org/maven2/ca/vanzyl/maven-sigstore-test/0.0.20/

I've talked with a few large open source Java projects who are willing to use this plugin as soon as it's available, so I think we can move fairly quickly getting the Maven/Java community onboarded.

Thanks,

Jason

**Comment by dlorenc** [comment]
I'm +1 on the move. I think @bobcallaway is willing to deprecate his: https://github.com/sigstore/sigstore-maven-plugin and mark it as archived.

Does that make sense to you Bob?

**Comment by bobcallaway** [comment]
Makes sense and I’m supportive.

**Comment by lukehinds** [comment]
approved: will ping you @jvanzyl about transfer.
