### ISSUE TITLE
Proposal to split the Documentation repo from the Sigstore WWW repo

### ISSUE THREAD

**Issue by ltagliaferri** [sigstore/TSC#18]
**Description**

I shared this with the community at the most recent contributors meeting, here is my full RFC doc: [Sigstore Docs -> Own Repo](https://docs.google.com/document/d/1ue9xFTXGvYHb3Pal8OqVsP-GEEQlHo70igrXLspG_TM/edit#heading=h.aszm56df7zup)

**Context**

Currently, Sigstore has its documentation in a branch on a repository that’s shared with the Sigstore www website (the “Marketing website”). 

This makes for a confusing user experience, and, in particular, creates barriers to entry for those in the community who want to contribute to documentation. Additionally, there are technical issues created from this (such as linking into the correct GitHub branch from the frontend of the site). 

**Proposal**

Separate Docs out from the Marketing website.

Keep sigstore.dev pointing to `sigstore/sigstore-website`, and create `sigstore/docs` for docs.sigstore.dev

| Goals      | Details |
| ----------- | ----------- |
| Support docs contributions      | Removing branch workflow will help newcomers contribute to docs, and also help developers with a less confusing workflow |
| Remove technical complexity   | Shared resources and a branch workflow make it challenging to identify how every piece of the site is working |
| Support different workflows with different functionalities for the Marketing site and the Docs site | The Marketing site and Docs site have little in common in terms of purpose, information architecture, and aesthetics. Breaking these sites up will enable each to develop on its own trajectory without being silo-ed with other static content |
| Keep docs updated and maintained | The repo-based docs are updated much more frequently than the current Docs site, resulting in the user’s first documentation touch point being subpar |
| Source of truth for all documentation | This should be the long-term goal for this repository in an effort to prevent documentation sharding and to be a clear source for developers and users of Sigstore |

Thank you for any feedback!

**Comment by dlorenc** [comment]
+1 on this.

**Comment by bobcallaway** [comment]
+1 on this as well.

**Comment by dlorenc** [comment]
Approved! Let me know how you want to do this @ltagliaferri. I can create a new repo called docs and then let you push the branch?

**Comment by lukehinds** [comment]
+1
