### ISSUE TITLE
Adoption of rekor-rs crate

### ISSUE THREAD

**Issue by lukehinds** [sigstore/TSC#19]
@jyotsna-penumaka would like to donate the a rust rekor crate to sigstore. 

https://github.com/jyotsna-penumaka/rekor-rs

The crate is seperate to sigstore-rs as it contains a lot of swagger generated code. It also makes sense to run separately for those who just want a rekor centric library only

The crate has undergone fairly extensive reviews

obviously a +1 from me

@dlorenc  / @bobcallaway ...

**Comment by dlorenc** [comment]
+1

**Comment by bobcallaway** [comment]
+1, who will be the maintainers besides @jyotsna-penumaka ?
