### ISSUE TITLE
Adoption of sigstore-js package

### ISSUE THREAD

**Issue by bdehamer** [sigstore/TSC#20]
GitHub has been working on a native JS implementation of the sigstore signing/verification mechanics

https://github.com/github/sigstore-js

There's lots of work still to do here still but we'd like to donate the library to the sigstore project.

**Comment by dlorenc** [comment]
I can't +1 this hard enough!

Incredible work, and can't wait to have this in the community!

**Comment by bobcallaway** [comment]
+1 from me as well. Looking forward to seeing this adopted more widely!

**Comment by lukehinds** [comment]
+1, all day!

**Comment by lukehinds** [comment]
BTW, we have an unanimous TAC decision here, so this does not need to wait for the next TAC meeting. We can get the repo transfer underway.

**Comment by cpanato** [comment]
+1

**Comment by dlorenc** [comment]
@bdehamer feel free to reach out in slack to coordinate the transfer!

**Comment by lukehinds** [comment]
> @bdehamer feel free to reach out in slack to coordinate the transfer!

let me know when gone through and can drop something onto @projectsigstore twitter.

**Comment by bdehamer** [comment]
Working through some stuff on my side to get it transferred over. Thanks to the TSC for the support!

**Comment by bdehamer** [comment]
Done!

https://github.com/sigstore/sigstore-js
