### ISSUE TITLE
Transfer `gh-action-sigstore-python` to the `sigstore` org

### ISSUE THREAD

**Issue by tetsuo-cpp** [sigstore/TSC#30]
**Description**

We've recently put together a GitHub Action for using `sigstore-python` which can be found [here](https://github.com/trailofbits/gh-action-sigstore-python). At the moment, we expose configuration that covers `sigstore-python`'s signing functionality as well as some basic verification functionality.

As of right now, we've been dogfooding this Action by using it with [pip-audit](https://github.com/trailofbits/pip-audit) as well as @di's [pip-api](https://github.com/di/pip-api).

We'd like to transfer the project to https://github.com/sigstore org prior to the stable releases of both `sigstore-python` and `gh-action-sigstore-python`.

Initial maintainers would be:
- @woodruffw
- @di 
- Myself

In the meantime, I'll work on getting @lukehinds added as a collaborator to the repo so that the transfer can be made in the case that the TSC is happy with this.

**Comment by bobcallaway** [comment]
+1

**Comment by dlorenc** [comment]
+1

**Comment by tetsuo-cpp** [comment]
Friendly ping! Is there anything needed on my end to close this out?

**Comment by bobcallaway** [comment]
@lukehinds @trevrosen @SantiagoTorres need your vote pls

**Comment by dlorenc** [comment]
LGTM

**Comment by trevrosen** [comment]
+1

**Comment by bobcallaway** [comment]
@priyawadhwa @SantiagoTorres

**Comment by priyawadhwa** [comment]
+1!

**Comment by bobcallaway** [comment]
@tetsuo-cpp please go ahead and initiate the transfer to the sigstore org. Thanks!

**Comment by tetsuo-cpp** [comment]
@bobcallaway I'm talking with some people internally to give you the Admin role on the repo. I believe I can't transfer to the sigstore org since I'm not member of it.

**Comment by di** [comment]
I transferred it.

**Comment by bobcallaway** [comment]
thanks all!

**Comment by tetsuo-cpp** [comment]
Thank you!
