### ISSUE TITLE
Transfer timestamp-authority over to Sigstore

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/TSC#31]
**Description**

Repo: https://github.com/haydentherapper/timestamp-authority

Owners would be myself and @asraa initially. Repo is a WIP. It's mostly copied over from Rekor. We'll need to review the release configs to make sure they're still relevant/compatible with this repo.

I've validated both the server and CLI are functional.

**Comment by haydentherapper** [comment]
Will need a `tsa-codeowners` group created.

**Comment by dlorenc** [comment]
Can we get someone from one other company added as a maintainer? We've been requiring at least two vendors across other repos.

LGTM otherwise.

**Comment by haydentherapper** [comment]
Maybe someone from GitHub (@kommendorkapten?) after a couple of changes are made to the repo?

**Comment by kommendorkapten** [comment]
I'm up for it!

**Comment by dlorenc** [comment]
OK, I don't think we have to block on it, as long as there's a plan to get him on there!

**Comment by dlorenc** [comment]
In addition to the code itself, can we clarify in here (or maybe in the repo README) where we plan to run this service, and how it will fit into the overall TUF delegation? I know GitHub has discussed running one, but will we run one ourselves hosted somewhere at something like tsa.sigstore.dev?

**Comment by asraa** [comment]
> how it will fit into the overall TUF delegation?

We can define a new type of Usage: "TSA" and put the cert under a tsa/. GetTargetsByUsage will search for that usage type.

**Comment by dlorenc** [comment]
What's the expiry on the TSA cert going to look like?

**Comment by kommendorkapten** [comment]
> What's the expiry on the TSA cert going to look like?

I presume a cloud KMS with HSM would be used for this. One year to start with ok or too permissive?

**Comment by haydentherapper** [comment]
My plan was long lived, 10 years to align with fulcio, because we will effectively handle revocation and trust with its inclusion in the Tuf targets. 

For the signing key, I’m thinking of reusing what I implemented in fulcio, a Tink key set encrypted by a Kms key. All in memory, so scales well. It will also support Kms-based signing.

**Comment by trevrosen** [comment]
I’m happy to accelerate this in any way that I can. Plz let me know if there's anything I can help with regarding administrative tasks around repo move etc. 

FYI from our side @malancas will be taking lead on the dev and o11y stuff here, and @kommendorkapten will be involved in his role as overall tech lead for our sigstore initiatives.

**Comment by haydentherapper** [comment]
Repo is still a WIP, there's some dependency issues I'm working out now, but it can be transferred still. I'll try to work out the issues before transferring so we have a working service, but I'm fine with either moving now or later.

**Comment by dlorenc** [comment]
Is this ready to transfer?

**Comment by malancas** [comment]
@haydentherapper since I will be taking lead on the dev work from Github, I'm happy to help out or sync up as needed.

**Comment by haydentherapper** [comment]
This repo is ready to transfer - https://github.com/haydentherapper/timestamp-authority/pull/41 will make the TSA fully functional.

**Comment by bobcallaway** [comment]
LGTM to transfer; @priyawadhwa @lukehinds @SantiagoTorres need votes please

**Comment by lukehinds** [comment]
+1

**Comment by haydentherapper** [comment]
That's majority, so I'll start the transfer tomorrow morning.

**Comment by haydentherapper** [comment]
This is done.
