### ISSUE TITLE
Create new repo sigstore-devops-tools

### ISSUE THREAD

**Issue by cpanato** [sigstore/TSC#32]
**Description**

Request to create the repo: `sigstore-devops-tools`

spoke with Bob before and the idea of this repository is to host the tools and services that will support the development of the sigstore tools & services

for example:

- this will have a small function to check who is on-call for sigstore
- will have the github webhook function to work with release notes (see https://sigstore.slack.com/archives/C01DGF0G8U9/p1662017529021859)

and other possible services & tools to help the sigstore organization and maybe others as well :)

**Comment by cpanato** [comment]
since I forgot to open this issue and went ahead, this is the PR that creates the repo: https://github.com/sigstore/community/pull/118

**Comment by dlorenc** [comment]
LGTM

**Comment by bobcallaway** [comment]
LGTM

**Comment by lukehinds** [comment]
The TSC is just coming up, so we can vote in there.

**Comment by lukehinds** [comment]
approved

**Comment by dlorenc** [comment]
Can we close this out?
