### ISSUE TITLE
Proposal for Sigstore Community Awards

### ISSUE THREAD

**Issue by tracymiranda** [sigstore/TSC#33]
### Overview

This is a proposal for inaugural Sigstore community awards to be presented to key community members live at SigstoreCon on October 25th. 
Annual community awards are a great way to recognize the efforts of key individuals in the community and as a general celebration for the entire community. 

### Number of Awards
3 Sigstore Awards Total
- Most Valuable Contributor - for the individual who has made a huge impact to the project this year
- Best Evangelist - for the individual who has gone above and beyond to spread the word about sigstore
- Best User Adopter- to the individual, team or organization who have adopted sigstore and have shared their impactful story with others

### Award Nominations & Voting
A github issues is opened for each award on sigstore/community - the Sigstore community is invited to nominate potential recipients for each award.

A shortlist is created based on all eligible entries and the final voting is carried out by the Sigstore TSC. 

### Timeline 2022
Awards ordered: Monday, August 29
Nominations open: Tuesday, September 6, 2022
Nominations close: Tuesday, September 13, 2022
Voting opens: Thursday, September 15, 2022
Voting closes: Monday, September 26, 2022
Winner names sent to be engraved: Wednesday, September 28, 2022
Winners announced at SigstoreCon: Tuesday, October 25, 2022

### Details
  * Awards to be ordered from Pinnacle, budget of $1000 (including engraving) and shipped with rest of swag order
  * It may be awards are posted to recipient after ceremony if we cannot get them delivered in time (in which case we can extend the nomination and voting periods)

### GitHub Issue Sample Text for Award Nominations

Top Contributor
Issue name: [Nominations Open] Most Valuable Sigstore Contributor Award 2022 🏆

This issue is to receive nominations for the Most Valuable Sigstore Contributor Award 2022.

This award recognizes excellence of technical contributions to Sigstore. This individual commits key pieces to projects and, more importantly, contributes in a way that benefits the project neutrally as a whole.

To nominate someone, reply to this issue with the following:

1. Full name of the person you’re nominating
2. Short description of their contributions to Sigstore and why they should win.

Nomination Deadline: Tuesday, September 13, 2022

![Screen Shot 2022-09-01 at 9 48 36 AM](https://user-images.githubusercontent.com/5173122/187930444-dff7eeef-db57-4bfc-8171-1a73b39374e1.png)

**Comment by tracymiranda** [comment]
General consensus at the TSC meeting to move forward (with caveat that dates may need adjusting)  Next steps:

- [ ] submit PR for awards landing page in community repo
- [ ] create issues for 3 awards and announce at community meeting
- [ ] maybe a blog post/social to promote

**Comment by lukehinds** [comment]
closing as awards now complete

**Comment by tracymiranda** [comment]
Awards page can be seen here: https://github.com/sigstore/community/tree/main/awards
