### ISSUE TITLE
How should we be handling licenses for our dependencies?

### ISSUE THREAD

**Issue by vaikas** [sigstore/TSC#34]
**Question**
Currently there is some inconsistency in how we check / handle licenses. I'd like the TSC to step in and help us define the policy for these, so that we can then consistently apply them across the projects by setting up automation in each repo, that would be good :)

I filed this in cosign, but just raising awareness here, but here is the issue with some pointers:
https://github.com/sigstore/cosign/issues/2258

And some discussion:
https://github.com/sigstore/cosign/pull/2259

**Comment by bobcallaway** [comment]
adding to next TSC meeting agenda, thanks @vaikas
