### ISSUE TITLE
Priya Wadhwa TSC position

### ISSUE THREAD

**Issue by lukehinds** [sigstore/TSC#35]
As discussed on today's TSC call, this issue is to vote on the proposal of @priyawadhwa replacing @dlorenc on the TSC.

@trevrosen 
@bobcallaway 
@SantiagoTorres

**Comment by lukehinds** [comment]
+1 from me

**Comment by SantiagoTorres** [comment]
+1

**Comment by dlorenc** [comment]
+1 from me!

**Comment by trevrosen** [comment]
+1

**Comment by lukehinds** [comment]
sorry forget to tag @dlorenc

**Comment by bobcallaway** [comment]
+1

**Comment by dlorenc** [comment]
Congrats Sigstore, and welcome Priya!
