### ISSUE TITLE
Create a new 'protobuf' repository

### ISSUE THREAD

**Issue by patflynn** [sigstore/TSC#38]
As a result of the new [bundle work](https://github.com/sigstore/cosign/pull/2204), it looks like we have consensus that the project would benefit from storing the protos in a separate repo (from cosign) from which we can generate client libraries, potentially provide them, and/or automate their deployments to various package managers. 

Eventually we could imagine moving all new protobuf based APIs for the sigstore project into this repository to facilitate discovery and distribution. 

Suggested repository name: "protobuf"

**Comment by trevrosen** [comment]
+1 - IMO separate repo is vital and I'm excited to see this happen! 🎉

**Comment by dlorenc** [comment]
Strongly support this!

**Comment by woodruffw** [comment]
Not a TSC member but +1 to a separate repo!

**Comment by bobcallaway** [comment]
nit: could we name it `sigstore/protobuf-specs` instead?

**Comment by patflynn** [comment]
works for me. @kommendorkapten

**Comment by kommendorkapten** [comment]
@patflynn That name is good!

**Comment by lukehinds** [comment]
Gtm

**Comment by bobcallaway** [comment]
last question before we create this - who are the proposed maintainers?

**Comment by patflynn** [comment]
@znewman01 @haydentherapper @kommendorkapten @asra preferences?

**Comment by kommendorkapten** [comment]
I think @znewman01 @haydentherapper are good candidates. I can volunteer too if needed.

**Comment by bobcallaway** [comment]
If we anticipate that we'll move definitions over from Rekor and Fulcio, it would be nice to have at least one maintainer from those projects on this one as well. Not something we have to close on now but perhaps to keep in mind?

**Comment by haydentherapper** [comment]
Happy to help maintain for the bundle and for fulcio protos.

**Comment by asraa** [comment]
Big +1! It would be awesome to have for Rekor, and we can also include  schemas for TUF repository maps as that progresses and so on.
