### ISSUE TITLE
sigstore-go

### ISSUE THREAD

**Issue by lukehinds** [sigstore/TSC#39]
There has been many discussions on having a sigstore-go library, so this is a TSC request to start the project.

Initial maintainers can be @znewman01 and myself @lukehinds just to get things started, we can then easily add more  as needed. 

p.s. I thought this had already been raised and had created the repo already. I think its a given this will be approved though.

cc @trevrosen @bobcallaway @priyawadhwa @SantiagoTorres - please +1 or -1

**Comment by bobcallaway** [comment]
+1, thanks for doing this

**Comment by trevrosen** [comment]
+1 this is fantastic. 

( Cc @codysoyland who is enthusiastic to commit here! )

**Comment by priyawadhwa** [comment]
+1!

**Comment by SantiagoTorres** [comment]
+1!

**Comment by codysoyland** [comment]
+1! 🙌🏻

**Comment by lukehinds** [comment]
closing as approved
