### ISSUE TITLE
Migrate blog to github.

### ISSUE THREAD

**Issue by lukehinds** [sigstore/TSC#40]
Discussed this with @bobcallaway and I think it makes sense to migrate off medium to here. This was we can then use config to allocate approvers (TSC members) and have a review process. 

Anyone wanting to contribute at article can create an issue. 

tagging other TSC folks: @trevrosen @priyawadhwa @SantiagoTorres @bobcallaway

**Comment by trevrosen** [comment]
Wondering if we should clarify hosting and analytics before making this move 🤔

**Comment by davelester** [comment]
Re: analytics, perhaps we can use [GoatCounter](https://www.goatcounter.com/) which is currently used by the SLSA website. Analytics are also public which adds some transparency ([SLSA example](https://slsa.goatcounter.com)).

**Comment by joshuagl** [comment]
> Re: analytics, perhaps we can use [GoatCounter](https://www.goatcounter.com/) which is currently used by the SLSA website. Analytics are also public which adds some transparency ([SLSA example](https://slsa.goatcounter.com)).

I came here to make the same suggestion, thanks Dave.

Here's the SLSA PR where the change was introduced (including discussion of why it was the preferred option) https://github.com/slsa-framework/slsa/pull/262

**Comment by lukehinds** [comment]
Only one main guideline; it would be nice to get the blog looking similar to the main site https://sigstore.dev

Anyone who would like to try this, we can create a repo and get you set up!

**Comment by rchaganti** [comment]
@lukehinds I am commenting here based on our tweet exchange. I can set up a Hugo static site for this and integrate Goatcounter for analytics. With Hugo, everything gets written in markdown, and we use a GitHub action to publish the GitHub pages branch that will be served as blog.sigstore.dev. We can set up review workflows to ensure the article is reviewed and approved before publication.

Decisions to be made:
- Finalize using Hugo as the static site generator
- If going with Hugo, finalize a Hugo theme with scope for customization to look like sigstore.dev. 
- Finalize the commenting system. I am experimenting with [giscus](https://giscus.app/), which uses GitHub discussions in the repo to enable commenting.

What we would need:
- Need a GitHub repo with collaborator permissions.
- DNS changes (eventually) to point blog.sigstore.dev to the GitHub pages location generated by Hugo.
- Anything else I may have missed now! :)

**Comment by lukehinds** [comment]
hey @rchaganti , Many thanks for volunteering. I think you're approach is sound. I will start getting the repo set up this week.

Do you think its realistic to get something remotely similar to the main site? (https://sigstore.dev), if at the least the same color scheme?

**Comment by rchaganti** [comment]
@lukehinds I am working on a couple of Hugo themes. We should be able to match the color scheme and font for sure. I will post a few suggestions to vote on, and we can take it from there.

**Comment by lukehinds** [comment]
repo is in progress for setting up:

https://github.com/sigstore/sigstore-blog
https://github.com/sigstore/community/pull/204

**Comment by lukehinds** [comment]
Great work @rchaganti thank you!

**Comment by rchaganti** [comment]
@lukehinds I see seven posts on the blog.sigstore.dev site. And then I saw https://medium.com/@sigstore-editor, which has a few additional posts. Then, there is this -- https://medium.com/tag/sigstore. This final list has articles with a sigstore tag by any author on medium. In the 3rd list, if I eliminate the external authors, all articles published in Sigstore account to more than what I saw in the first two links.

Is there a single list of all articles we need to import to the new site?

**Comment by lukehinds** [comment]
yep, sorry about this @rchaganti , it is a mix of those. I think the issue is we originally had individual editors contribute, we then moved to having a dedicated 'sigstore' user and for some reason we stopped using that again. So its going to be an aggregation of all three.

**Comment by rchaganti** [comment]
Gotcha! I will start the migration. It will be a bit slow as I am on the move. I will confirm once I am done, and we will need a DNS entry (CNAME) to point blog.sigstore.dev to the GitHub pages. Can you create a goatcounter dashboard and give me the code?

**Comment by lukehinds** [comment]
Thanks!

> Can you create a goatcounter dashboard and give me the code?

I have never done this before, could you give me a hint as to what is involved?

**Comment by rchaganti** [comment]
https://www.goatcounter.com/signup 

Follow the form. I used sigstoreblogstage as the code to test integration and that becomes a part of the URL to access the dashboard.

**Comment by lukehinds** [comment]
```javascript
<script data-goatcounter="https://ovbfwhmermxjt4.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
```

**Comment by bobcallaway** [comment]
fyi, we also own `sigstore.blog` so I might go ahead and set that up now, and we can then redirect `blog.sigstore.dev` to that domain when we're ready.

**Comment by rchaganti** [comment]
@bobcallaway can you make changes to DNS to point sigstore.blog to the GitHub pages server IPs? I will add the CNAME and configure a custom domain in this repository.

**Comment by bobcallaway** [comment]
> @bobcallaway can you make changes to DNS to point sigstore.blog to the GitHub pages server IPs? I will add the CNAME and configure a custom domain in this repository.

https://sigstore.blog/ is live; I added CNAME and took care of the domain config in GitHub.

**Comment by rchaganti** [comment]
I see there was a new post published yesterday. I will migrate that. What is the plan going forward? Can we have content route through this new blog repo?

**Comment by rchaganti** [comment]
@bobcallaway, do you own sigstore.dev DNS? Can you redirect blog.sigstore.dev to sigstore.blog?

**Comment by bobcallaway** [comment]
Once we get the ACK from the TSC that this is good to go, yes I can process the DNS change to create a CNAME record for `blog.sigstore.dev` to point to `sigstore.blog`.
