### ISSUE TITLE
RFC: Migrate `trailofbits/sigstore-conformance` to the Sigstore GitHub org

### ISSUE THREAD

**Issue by woodruffw** [sigstore/TSC#42]
Hello TSC!

This is a general RFC/discussion tracker for a repository migration request: I'd like to migrate [`trailofbits/sigstore-conformance`](https://github.com/trailofbits/sigstore-conformance) to the Sigstore org, ideally living under the same repo name or just "conformance" (so `sigstore/sigstore-conformance` or `sigstore/conformance`).

For context: my company (Trail of Bits) is currently being contracted to work on various aspects of the Sigstore ecosystem. We're primarily focused on the Python implementation of Sigstore, but we've also been tasked with developing a reusable conformance test suite that each implementation of Sigstore can drop into their CI (via a GitHub Action we provide).

We're currently performing that work under our own GitHub org, but IMO re-homing it makes sense in terms of ecosystem integrity/shared ownership. Precedent for this includes the last two repos we migrated (`sigstore-python` and `gh-action-sigstore-python`).

cc @di and @tetsuo-cpp for visibility.

**Comment by bobcallaway** [comment]
LGTM

**Comment by bobcallaway** [comment]
@lukehinds @priyawadhwa @trevrosen @SantiagoTorres please weigh in - thanks!

**Comment by SantiagoTorres** [comment]
This makes sense to me. As an immediate follow up I'd say it'd be good to be able to streamline the integration between this and sigstore/sigstore-go and the other languages

**Comment by priyawadhwa** [comment]
LGTM!

**Comment by lukehinds** [comment]
+1

**Comment by woodruffw** [comment]
Sounds like there's consensus 🙂 -- can someone volunteer to be the TSC liaison so that I can add them to the `sigstore-conformance` repo and get it moved over to the `sigstore` org?

**Comment by bobcallaway** [comment]
> Sounds like there's consensus slightly_smiling_face -- can someone volunteer to be the TSC liaison so that I can add them to the `sigstore-conformance` repo and get it moved over to the `sigstore` org?

I can help with this!

**Comment by woodruffw** [comment]
> I can help with this!

Awesome! I'll make you an owner on the current ToB org repo; that should give you permission to migrate it.

**Comment by woodruffw** [comment]
@bobcallaway you should be an admin now, so you should be entitled to move the repo!

**Comment by bobcallaway** [comment]
repo moved, making changes in sigstore/community to bring it under pulumi control.

**Comment by woodruffw** [comment]
Complete!
