### ISSUE TITLE
New Public Repo: ops or public-ops?

### ISSUE THREAD

**Issue by pwelch** [sigstore/TSC#43]
**Description**

The on-call group has been discussing a location to keep public post-mortems. We would like to create a public repo that we can publish any public post-mortem details and potentially other resources that we want available for public consumption regarding the public good instance. 

We discussed calling it `sigstore/ops` or `sigstore/public-ops` but are open to other names because naming is hard.

**Comment by priyawadhwa** [comment]
Thanks for opening the issue @pwelch! After giving it a second thought, WDYT of adding a folder to [sigstore/community](https://github.com/sigstore/community)? I'm wondering if we're more likely to get eyes on post-mortems if it's in community 🤔

**Comment by pwelch** [comment]
@priyawadhwa Ah! I didn't realize we have that repo. We'll add public incident reports there. Thanks!
