### ISSUE TITLE
Project promotion for timestamp authority

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/TSC#44]
Hi TSC, as there are no remaining features or high priority issues to complete for the [timestamp authority](https://github.com/sigstore/timestamp-authority) repository, I'd like to propose that we release 1.0 soon. I'd like to target 1.0 by end of February, so I would propose cutting a release candidate soon and releasing 1.0 a few weeks after.

What does the project promotion look like? Should this repo be a part of the landscape? Does it need a logo?

cc @malancas @trevrosen @lukehinds

**Comment by trevrosen** [comment]
lgtm for me on 1.0. Personally I don't think it needs a logo.

**Comment by haydentherapper** [comment]
![image](https://user-images.githubusercontent.com/8418760/213557413-165b31d1-25d0-41ac-9603-aaac7acdeeb6.png)

**Comment by trevrosen** [comment]
😹 

My reasoning is that it's basically an implementation of an RFC and is an implementation detail of our trust model and not really A Thing™ in its own right. But other folks may have other opinions here, and mine's not too strong on this one. 😄

**Comment by hectorj2f** [comment]
Happy to help promoting it! We're also using the Sigstore TSA implementation.

**Comment by dlorenc** [comment]
Even though you don't need a logo I can imagine some cool ones :)

Some kind of cool hourglass, stopwatch, or sundial theme would be awesome!

**Comment by tracymiranda** [comment]
For the landscape we could put it under 'Deployments' which we could rename 'Services' to reflect all the public services that Sigstore offers? Though have seen @trevrosen that maybe it's not all that user/public facing... 

I can kick off a request for some logo ideas...

**Comment by haydentherapper** [comment]
Thanks all! I'll work on releasing a 1.0 RC then for this. Agreed that it's different than existing services, so I'm fine with either including it or not on the landscape, since like Trevor said, it's an implementation of an RFC.
