### ISSUE TITLE
Adopt model_transparency (ML model signing)

### ISSUE THREAD

**Issue by mihaimaruseac** [sigstore/TSC#49]
Hello,

We were thinking to migrate https://github.com/google/model-transparency to be under Sigstore since it is a wrapper around Sigstore for signing AI models. We have launched the project in Q3 last year under the Google organization to experiment, but as we are now looking to engage external organizations, we feel it is better to move its home to Sigstore.

So far, the only contributors to the model transparency repository are also active in Sigstore community.

Thank you

**Comment by dlorenc** [comment]
This sounds awesome, +1 from me! (non binding of course)

**Comment by bobcallaway** [comment]
@sigstore/core-team FYI for review

**Comment by SantiagoTorres** [comment]
+1 from me!

**Comment by bobcallaway** [comment]
LGTM

**Comment by trevrosen** [comment]
Love it! +1

**Comment by priyawadhwa** [comment]
lgtm!

**Comment by lukehinds** [comment]
I totally missed this! 

very much +1

**Comment by bobcallaway** [comment]
unanimous votes in support of proposal, approved
