### ISSUE TITLE
Repo Cleanup

### ISSUE THREAD

**Issue by dlorenc** [sigstore/TSC#7]
We have quite a few stale repos, let's use this to track their cleanup!

**Comment by dlorenc** [comment]
I think these can probably get deleted/archived:
* https://github.com/sigstore/rekorctl 
*  https://github.com/sigstore/rekor-monitor
* https://github.com/sigstore/examples]
* https://github.com/sigstore/sigstore-helm-operator
* https://github.com/sigstore/sigstore-git-verifier

**Comment by lukehinds** [comment]
https://github.com/sigstore/sigstore-helm-operator/issues/9

**Comment by lukehinds** [comment]
closing as all archived now
